# Generated by Django 5.2 on 2025-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
