# Generated by Django 5.2 on 2025-06-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0002_add_timestamp_to_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="filename",
            new_name="basename",
        ),
        migrations.AddField(
            model_name="entry",
            name="filenames",
            field=models.JSONField(default=list),
        ),
    ]
