# Generated by Django 5.2 on 2025-06-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0003_rename_filename_entry_basename_entry_filenames"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="directory",
            field=models.CharField(default="..", max_length=255),
            preserve_default=False,
        ),
    ]
