# Generated by Django 5.2 on 2025-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0004_gallery_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="directory",
            field=models.CharField(default=".", max_length=255),
        ),
    ]
