# Generated by Django 5.2 on 2025-06-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0005_entry_hidden_alter_gallery_directory"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entry",
            unique_together={("gallery", "order")},
        ),
    ]
