# Generated by Django 5.2 on 2025-06-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0006_alter_entry_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
