# Generated by Django 5.2 on 2025-06-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0007_add_width_height_to_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="caption",
            field=models.TextField(blank=True),
        ),
    ]
