# Generated by Django 5.2 on 2025-06-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0008_alter_entry_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="mtimes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
