# Generated by Django 5.2 on 2025-06-20 19:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery2", "0011_entry_video_mtimes"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="og_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="og_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
